source 'https://rubygems.org'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'faker'
gem 'nokogiri'
gem 'rspec'
gem 'cucumber-api'
gem 'test-unit'
gem 'minitest'
gem 'rest-client'
gem 'capybara'
gem 'rubocop'
gem 'yard'
gem "parallel_tests"
gem "poltergeist"
gem "json_pure"
gem "cuke_sniffer"
gem "parallel"
gem "json"
gem "rake"
gem "yard-cucumber"
gem "redcarpet"
gem 'site_prism'
gem "show_me_the_cookies"
gem 'relish'
gem 'factory_girl'
gem 'rubocop-checkstyle_formatter'
gem 'wannabe_bool'
gem 'chromedriver-helper'
gem 'appium_lib'
gem 'appium_console'
gem 'page-object'
gem 'pry-rails'
gem 'pry-byebug'
gem 'require_all'
gem 'phantomjs'
gem 'webmock'
gem 'vcr'
gem 'rack-test'
gem 'sshkit'
gem 'sinatra'
gem "haml"
gem "rdiscount"
gem "gherkin"
gem "gherkin3"
gem "komainu"
gem "mongo_mapper"
gem "bson_ext"
gem "fakefs"
gem "launchy"
gem "pretty_face"
#gem "pg"
